# Generated by Django 3.1.14 on 2022-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20220427_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='bulbazavr.png', upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
